### ISSUE TITLE
UpSert flag is broken

### ISSUE THREAD

**Issue by carolynvs** [MChorfa/porter-helm3#16]
The upsert flag is broken because it is mapped to the wrong yaml tag.

https://github.com/MChorfa/porter-helm3/blob/f2012f4eb0ed53290e13f4a344bdd56b194d9f45/pkg/helm3/install.go#L32

I suggest that install and upgrade should unconditionally run `helm upgrade --install` instead of having it be a flag. We should make the same change to the helm2 mixin as well! 😊 

One of the rules of a mixin is that it should allow the user to wrap imperative CLI commands (like helm install) in a more desired state or idemponent (retryable) fashion. Due to the nature of bundles, we have to design for every bundle action to be rerun. This is why for example the [helm2 mixin gracefully handles errors](
https://github.com/getporter/helm-mixin/blob/9fa978eb975e8704e92cb7f8f146df6b2370cabc/pkg/helm/uninstall.go#L53-L61) when trying to delete a release that is already deleted.

I would be happy to submit a PR for this is you agree.

**Comment by MChorfa** [comment]
Thank you @carolynvs  for pointing out the broken flag.  I'll make the necessary changes

**Comment by carolynvs** [comment]
Cool, I wasn't familiar with --atomic but  it seems perfect for the mixin! 👍

**Comment by carolynvs** [comment]
@MChorfa You had a lot of good ideas in your last comment on this issue. Maybe we should copy them over to a new issue, for the flags like --atomic?

**Comment by MChorfa** [comment]
The `--atomic` is now part of the build command released within v0.1.13, where:
- on installation action where the installation process deletes the installation on failure.
- on the upgrade process rolls back changes made in case of a failed upgrade.
