### ISSUE TITLE
Remove temporary zip file in docker build to trim the porter invocation image

### ISSUE THREAD

**Issue by jasmdk** [MChorfa/porter-helm3#18]
When installing the helm3 binary (https://github.com/MChorfa/porter-helm3/blob/master/pkg/helm3/build.go) a tar.gz file is downloaded and unarchived, but the file remains in an image which already is quite large.

**Comment by carolynvs** [comment]
This fix is available in the latest release (v0.1.13).

https://github.com/MChorfa/porter-helm3/blob/e643fad90573f208b68577d917708462986f5eb8/pkg/helm3/build.go#L82

**Comment by MChorfa** [comment]
Closing this issue This fix is available in the latest release (v0.1.13).
