### ISSUE TITLE
atom.xml file is no longer available at the path written in documentation

### ISSUE THREAD

**Issue by jasmdk** [MChorfa/porter-helm3#19]
The link https://mchorfa.github.com/porter-helm3/atom.xml results in 404 Not Found

**Comment by jasmdk** [comment]
Documentation should be changed to https://mchorfa.github.io/porter-helm3/atom.xml due to this: https://github.blog/changelog/2021-01-29-github-pages-will-stop-redirecting-pages-sites-from-github-com-after-april-15-2021/

**Comment by jarnfast** [comment]
@jasmdk @MChorfa I created a PR that will fix the problem going forward.
Existing users of the mix-in will still need to update their reference manually.
