### ISSUE TITLE
does not add helm3 repo update to dockerfile

### ISSUE THREAD

**Issue by squillace** [MChorfa/porter-helm3#9]
I'd love it if we could add the following line here: https://github.com/MChorfa/porter-helm3/blob/9324ef661a303a99e194e419173b41fb10761ddb/pkg/helm3/build.go#L82

--> `fmt.Fprintf(m.Out, "\nRUN helm3 repo update)`

so that AFTER adding all the repositories, we called repo UPDATE at build time, so that no one ever updates at runtime. What a waste that is.

**Comment by MChorfa** [comment]
Introduced in v0.1.9
